export const INTERESTS = [
    { id: 1, name: "Business", icon: "💼" },
    { id: 2, name: "Science & Tech", icon: "🔬" },
    { id: 3, name: "Music", icon: "🎵" },
    { id: 4, name: "Entertainment", icon: "🎬" },
    { id: 5, name: "Arts", icon: "🎨" },
    { id: 6, name: "Health", icon: "❤️" },
    { id: 7, name: "Travel", icon: "✈️" },
    { id: 8, name: "Sports", icon: "🏀" },
    { id: 9, name: "Fashion", icon: "👗" },
    { id: 10, name: "Food", icon: "🍔" },
    { id: 11, name: "Charities", icon: "🎗️" },
    { id: 12, name: "Government", icon: "🏛️" },
    { id: 13, name: "Community", icon: "🤝" },
    { id: 14, name: "Spirituality", icon: "🛐" },
    { id: 15, name: "Family", icon: "👨‍👩‍👧‍👦" },
    { id: 16, name: "Seasonal", icon: "🍁" },
    { id: 17, name: "Home", icon: "🏡" },
    { id: 18, name: "Auto, Boat & Air", icon: "🚗" },
    { id: 19, name: "School Activity", icon: "🏫" },
];
